name: IMAGINE Research Group
url: http://imagine.uniandes.edu.co

exclude: [bibble, README.md, Makefile, screenshot.png, publications.html]

# colorize code snippets with the pygments module
# highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty

  # - key: staff
  #   name: Staff
  # - key: postdoc
  #   name: Researchers
  - key: grad
    name: Graduate Students
  - key: ugrad
    name: Undergraduate Students
  - key: alum
    name: Alumni
  - key: ugrad-alum
    name: Past Undergraduate Students
  - key: collab
    name: Collaborators
  - key: phd
    name: PHD Students
  - key: master
    name: Masters Students
  - key: phd-alum
    name: Past PHD Students
  - key: master-alum
    name: Past Masters Students
  


defaults:
  - scope:
      path: ""
      type: projects
    values:
      research_area: Human Computer Interaction



# Number of news stories on the front page.
front_page_news: 2

# Base pathname for links.
base: ''
# base: '/public'

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /#people
  - title: Research
    link: /research.html
  - title: Legacy
    link: /legacy.html
  #- title: Schedule
   # link: /schedule.html
  # - title: Publications
  #   link: /publications.html
  - title: Partners
    link: /partners.html
